package exh.source

object ExhPreferenceKeys {
    const val SHOULD_AUTO_UPDATE = "should_auto_update"
    const val HENTAI_ENABLED = "eh_is_hentai_enabled"
    const val INCOGNITO_MODE = "eh_incognito_mode"
    const val ENABLE_EXHENTAI = "enable_exhentai"
    const val IMAGE_QUALITY = "ehentai_quality"
    const val USE_HENTAI_AT_HOME = "eh_enable_hah"
    const val USE_JAPANESE_TITLE = "use_jp_title"
    const val USE_ORIGINAL_IMAGES = "eh_useOrigImages"
    const val TAG_FILTER_VALUE = "eh_tag_filtering_value"
    const val TAG_WATCHING_VALUE = "eh_tag_watching_value"
    const val MEMBER_ID = "eh_ipb_member_id"
    const val PASS_HASH = "eh_ipb_pass_hash"
    const val IGNEOUS = "eh_igneous"
    const val EH_SETTINGS_PROFILE = "eh_ehSettingsProfile"
    const val EXH_SETTINGS_PROFILE = "eh_exhSettingsProfile"
    const val SETTINGS_KEY = "eh_settingsKey"
    const val SESSION_COOKIE = "eh_sessionCookie"
    const val HATH_PERKS_COOKIE = "eh_hathPerksCookie"
    const val SHOW_SYNC_INTRO = "eh_show_sync_intro"
    const val READ_ONLY_SYNC = "eh_sync_read_only"
    const val LENIENT_SYNC = "eh_lenient_sync"
    const val SHOW_SETTINGS_UPLOAD_WARNING = "eh_showSettingsUploadWarning2"
    const val LOG_LEVEL = "eh_log_level"
    const val AUTO_UPDATE_FREQUENCY = "eh_auto_update_frequency"
    const val AUTO_UPDATE_REQUIREMENTS = "eh_auto_update_restrictions"
    const val AUTO_UPDATE_STATS = "eh_auto_update_stats"
    const val WATCHED_LIST_DEFAULT_STATE = "eh_watched_list_default_state"
    const val SETTINGS_LANGUAGES = "eh_settings_languages"
    const val ENABLED_CATEGORIES = "eh_enabled_categories"
    const val ENHANCED_EHENTAI_VIEW = "enhanced_e_hentai_view"
}
